#!/bin/bash

RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
LIGHT_BLUE='\033[1;34m'
GREEN='\033[0;32m'
GREEN_B='\033[1;32m'
YELLOW='\033[1;33m'
LIGHT_BLUE='\033[1;34m'
WHITE_B='\033[1m'
NC='\033[0m' # No Color

printf "		  ${LIGHT_GREEN}______________________\n"
printf "		  | ASSEMBLER CHECKER |${NC}\n"
printf "		  ${LIGHT_GREEN}______________________\n${NC}"

# printf "${YELLOW}Recompile the project${NC}\n"
# make re

# These are variables
DIR="champs_for_asm_checker/"
EXT_S=".s"
EXT_COR=".cor"
EXT_HEX=".hex"
ORIG="or_"
MY="my_"

FILE1="./or_asm"
if ! test -f "./or_asm" || ! test -f "./my_asm" ; then
	printf "${WHITE_B}Please provide ./or_asm AND ./my_asm files. Now exiting.\n${NC}"
	exit 1
fi

for filename in ${DIR}*.s; do
	FILE_S=$(basename -- "$filename")
	FILE_S="${FILE_S%.*}"

	# We create .cor files using or_asm and my_asm
	# and move them to the directory ${DIR}
	./or_asm "${DIR}${FILE_S}${EXT_S}"		
	mv "${DIR}${FILE_S}${EXT_COR}" "${DIR}${ORIG}${FILE_S}${EXT_COR}"
	./my_asm "${DIR}${FILE_S}${EXT_S}"
	mv "${DIR}${FILE_S}${EXT_COR}" "${DIR}${MY}${FILE_S}${EXT_COR}"

	# We create hexdump from orignal asm work
	FILE="${DIR}${ORIG}${FILE_S}${EXT_COR}"
	if test -f "$FILE"
	then
		printf "${GREEN_B}${ORIG}${FILE_S}${EXT_COR}${GREEN} exists.\n${NC}"
		hexdump -vC ${DIR}${ORIG}${FILE_S}${EXT_COR} > ${DIR}${ORIG}${FILE_S}${EXT_HEX}
		printf "    ${GREEN_B}${ORIG}${FILE_S}${EXT_HEX}${GREEN} created.\n${NC}"
	else
		printf "${RED}${ORIG}${FILE_S}${EXT_COR} DOESN'T exist.\n${NC}"
	# do break in cycle
	fi

	# We create hexdump from our asm work
	FILE="${DIR}${MY}${FILE_S}${EXT_COR}"
	if test -f "$FILE"
	then
		printf "${GREEN_B}${MY}${FILE_S}${EXT_COR}${GREEN} exists.\n${NC}"
		hexdump -vC ${DIR}${MY}${FILE_S}${EXT_COR} > ${DIR}${MY}${FILE_S}${EXT_HEX}
		printf "    ${GREEN_B}${MY}${FILE_S}${EXT_HEX}${GREEN} created.\n${NC}"
	else
		printf "${RED}${MY}${FILE_S}${EXT_COR} DOESN'T exist.\n${NC}"
	# do break in cycle
	fi

	# we check if both .cor files exist or don't exist simultaneously.
	FILE1="${DIR}${ORIG}${FILE_S}${EXT_HEX}"
	FILE2="${DIR}${MY}${FILE_S}${EXT_HEX}"
	if test -f "$FILE1" && test -f "$FILE2"
	then
		var=$(diff ${DIR}${ORIG}${FILE_S}${EXT_HEX} ${DIR}${MY}${FILE_S}${EXT_HEX})
		if [ -z "$var" ]
		then
			printf "${GREEN}For ${FILE_S}${EXT_S} ASM worked${LIGHT_GREEN} OK${NC}\n"
		else
			printf "${RED}For ${FILE_S}${EXT_S} ASM worked${LIGHT_RED} KO${NC}\n"
		fi
	elif ! test -f "$FILE1" && ! test -f "$FILE2"
	then
		printf "${GREEN}both ${GREEN_B}.cor files ${GREEN} don't exist.${GREEN_B}OK\n${NC}"
	else
		printf "${RED} Something wrong. ${RED_B} KO.\n${NC}"
	fi

	# Now delete all created files except the original champion which is *.s
	printf "Deleted: "
	FILE="${DIR}${MY}${FILE_S}${EXT_HEX}"
	if test -f "$FILE"; then
		rm ${FILE}
		printf "${ORIG}${FILE_S}${EXT_CORX} "
	fi

	FILE="${DIR}${ORIG}${FILE_S}${EXT_HEX}"
	if test -f "$FILE"; then
		rm ${FILE}
		printf "${MY}${FILE_S}${EXT_COR} "
	fi

	FILE="${DIR}${MY}${FILE_S}${EXT_COR}"
	if test -f "$FILE"; then
		rm ${FILE}
		printf "${ORIG}${FILE_S}${EXT_HEX} "
	fi

	FILE="${DIR}${ORIG}${FILE_S}${EXT_COR}"
	if test -f "$FILE"; then
		rm ${FILE}
		printf "${MY}${FILE_S}${EXT_HEX}\n\n"
	else
		printf "nothing.\n\n"
	fi
done
