#!/bin/bash

RED='\033[0;31m'
RED_B='\033[1;31m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
LIGHT_BLUE='\033[1;34m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
CYAN_B='\033[1;36m'
YELLOW='\033[1;33m'
WHITE_B='\033[1m'
NC='\033[0m' # No Color

printf "		  ${LIGHT_BLUE}______________________\n"
printf "		  | Check disassembler |${NC}\n"
printf "		  ${LIGHT_BLUE}______________________\n"

printf "${YELLOW}Recompile the project${NC}\n"
make re

DIR="champ_examples/"
DIS="_dis"
EXT_S=".s"
EXT_COR=".cor"
MD5="md5_"
ORIG="_or"
MY="_my"
FILE_S="turtle"

for filename in ${DIR}*.s; do
	FILE_S=$(basename -- "$filename")
	printf "\t${CYAN_B}Processing ${FILE_S}\n ${NC}"
	FILE_S="${FILE_S%.*}"
	./or_asm ${DIR}${FILE_S}${EXT_S}
	#we check if the *.cor from original *.s file is present
	if ! test -f "${DIR}${FILE_S}${EXT_COR}"; then
		printf "${RED}${FILE_S}${EXT_COR} not found.${NC}\n"
		printf "${YELLOW}swithching to next one \n ${NC}"
		continue
	fi

	./disasm ${DIR}${FILE_S}${EXT_COR} > ${DIR}${FILE_S}${DIS}${EXT_S}
	./or_asm ${DIR}${FILE_S}${DIS}${EXT_S}

	# we make md5 which calculates hash for both .cor files
	md5 ${DIR}${FILE_S}${EXT_COR} | sed 's|.*=||' > ${DIR}${MD5}${FILE_S}${ORIG}
	md5 ${DIR}${FILE_S}${DIS}${EXT_COR} | sed 's|.*=||' > ${DIR}${MD5}${FILE_S}${MY}

	# we look the difference between hashes
	var=$(diff ${DIR}${MD5}${FILE_S}${ORIG} ${DIR}${MD5}${FILE_S}${MY})
	if [ -z "$var" ]; then
		printf "${LIGHT_GREEN}${FILE_S}${EXT_S}:${GREEN} OK${NC}\n"
	else
		printf "${LIGHT_RED}${FILE_S}${EXT_S}:${RED} KO${NC}\n"
	fi
	# we delete both .cor files, both md5 files which contain hash and .s 
	# file which is generated from disassembly  
	rm ${DIR}${FILE_S}${EXT_COR}
	rm ${DIR}${FILE_S}${DIS}${EXT_COR}
	rm ${DIR}${MD5}${FILE_S}${MY}
	rm ${DIR}${MD5}${FILE_S}${ORIG}
	rm ${DIR}${FILE_S}${DIS}${EXT_S}
done
